### ISSUE TITLE
Feature Request: Allow Inversion of Colour scheme

### ISSUE THREAD

**Issue by jammiemil** [nikos/grafana-percent-trend-panel#10]
Thanks for the new panel, this is one of the tidier comparison plugins I've seen :)

One thing that would be nice to have would be to be able to invert the red/green + up/down relationship for values where and increase is bad rather than good.

For example in the below image i would want the default behaviour for 'Allowed' as an increased in Allowed items is Good, but an increase in Blocked items is bad so i would like the comparison to be red in the right hand panel:

![image](https://user-images.githubusercontent.com/54275278/195333329-dc46b2fe-343e-4cbc-a80c-570ca4b44eef.png)

**Comment by nikos** [comment]
Thanks for the kind words and great suggestion. Will have a look at it next week (currently on vacation), or you might want to open an PR?

**Comment by jammiemil** [comment]
I considered it but i have zero typescript experience and I'm still recovering from giving myself a crash course in golang....

**Comment by nikos** [comment]
Implemented as part of 1.0.5 release
