### ISSUE TITLE
Showing number with local format

### ISSUE THREAD

**Issue by itsnull12** [nikos/grafana-percent-trend-panel#15]
Hi mate, i really love this panel but i have a issue, when i want result of query number with local format, i got error "Invalid digits value: -1"

With unit > number : 100000

![image](https://user-images.githubusercontent.com/81866625/197459258-00da83a6-f88f-443f-bdd6-c1a851690f49.png)

I need with local format : 100,000

![image](https://user-images.githubusercontent.com/81866625/197459177-931304a3-dff6-4a3d-a140-28e51bf01431.png)

Can u help me please ? Thank you :)

**Comment by nikos** [comment]
Thanks @itsnull12 for reporting, this will be fixed in the next release 1.0.6
